apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.testEnv.envName }}-{{ .Values.app.name }}
spec:
  replicas: {{ .Values.testEnv.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
  
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
          - containerPort: {{ .Values.container.port }}
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "980Mi"
            cpu: "1000m"
      
